### PR TITLE
Remove direct dependency on Rails

### LINKED ISSUE #3: Depends on Rails directly
This Administrate plugin depends on Rails directly, and requires an old version as well. I think this dependency could be removed, leaving only Administrate, which itself depends on the necessary Rails components.

### PR DESCRIPTION
**Pull request by noahsettersten**
Instead of directly depending on Rails for this gem, this change removes that direct dependency and now follows Administrate's dependency on Rails.

Resolves #3

### CODE REVIEW

**Review by timgremore — COMMENTED** [review]
@noahsettersten Thanks for keeping this up! Do you have an app to verify this change in? Just curious cause I don't have anything to pull this into and test.

**Comment by noahsettersten** [comment]
@timgremore I'm working on updating a Rails app to 6.0 right now, and am relaxing these versions to allow for the upgrade to continue. So far, everything appears to be working well after the I18n ArgumentError fix, although the app surface is fairly small.

**Review by timgremore — APPROVED** [review]
LGTM!

**Comment by noahsettersten** [comment]
Thanks Tim! Do you know who has access to publish a new version to Rubygems?

**Comment by timgremore** [comment]
> Thanks Tim! Do you know who has access to publish a new version to Rubygems?

I don't. Might be best to ask that in #development

**Pull request merged**
